### ISSUE TITLE
Just not Working for me.

### ISSUE THREAD

**Issue by Hochstetko** [Spillmaker/Bagnon_Currencies#10]
Running 9.1
- Added to my bagnon, Have Databroker plugins off and still not working.
- not showing any checked currency.

**Comment by KiM38RuS** [comment]
I was a real fool xD I thought that the addon is not working but once accidentally pressed a button left from Databroker and currencies shown up =D

**Comment by Spillmaker** [comment]
Hi yall!

The addon is now updated to support both current version of Retail and WOTLK classic.
