### ISSUE TITLE
The Addons doesn't seem to work in WOTLK

### ISSUE THREAD

**Issue by Fedekielle** [Spillmaker/Bagnon_Currencies#13]
Hello sir

First and foremost, Thank you so much for updating this to WOTLK! 

I have installed both Bagnon and Bagnon Currencies, but I still can't get the currencies to show on my bags? (Yes they are enabled in the currency's tab to show on bags)

**Comment by MadSandwich** [comment]
@Spillmaker could you please take a look?
I'm facing the same issue, here a scrrenshot from the game
![image](https://user-images.githubusercontent.com/57759145/193458956-920f40ad-3dde-4ba7-88bc-ca6756b9f457.png)

**Comment by Spillmaker** [comment]
@MadSandwich Hello! It seems like databroker isnt showing in Bagnon for you. Make sure that its enabled in settings (Make sure that "Databroker Plugin" is checked): 
![image](https://user-images.githubusercontent.com/696120/193459061-8cb80755-684f-43e0-8620-3ee39a381ced.png)

@Fedekielle is this the same issue you have?

**Comment by MadSandwich** [comment]
@Spillmaker I've tried to enebale it, re-check currencies, relog into the game and for now just 'loading currencies'
![image](https://user-images.githubusercontent.com/57759145/193460802-d6a4db4c-7d57-4054-a5c2-9cf641dfeb46.png)

**Comment by Spillmaker** [comment]
@MadSandwich Hmm that is indeed strange

What version of Bagnon and Bagnon-Currencies do you have installed? If i get that i can try to troubleshoot more :)

**Comment by MadSandwich** [comment]
@Spillmaker sure, here my versions
![image](https://user-images.githubusercontent.com/57759145/193461655-b61d0a59-cd23-4e56-ae17-81d427a907fc.png)
And maybe if it would help, I have russian version of wow, maybe it some i18n issue? or you plugin support other languages?

**Comment by Fedekielle** [comment]
I live in Denmark and use the versions below.

When I enable "Datebroker plugin" - I get the option to view between different addons like Details og Bigwigs for example - not currency.

<img width="924" alt="Skærmbillede 2022-10-02 kl  17 35 30" src="https://user-images.githubusercontent.com/114223928/193462491-65b8b1dd-41ed-4002-a725-35f23b9283b2.png">

**Comment by Fedekielle** [comment]
Examples of the above mentioned addons that show when Databroker plugin is enabled.
<img width="285" alt="Skærmbillede 2022-10-02 kl  18 53 10" src="https://user-images.githubusercontent.com/114223928/193466241-7c4328eb-051d-4365-9dd0-1c6666caebf2.png">
<img width="261" alt="Skærmbillede 2022-10-02 kl  18 53 15" src="https://user-images.githubusercontent.com/114223928/193466243-8c26b6ac-7607-4c95-9091-8ebdb3df927b.png">
<img width="288" alt="Skærmbillede 2022-10-02 kl  18 53 18" src="https://user-images.githubusercontent.com/114223928/193466245-907e191c-8cfc-44b4-b0f4-9c60600464ba.png">

**Comment by Spillmaker** [comment]
@Fedekielle I suspect that Bagnon_currencies may not be enabled in that case. Are you sure its enabled in the addon-list?

@MadSandwich I managed to replicate this during a disconnect, and it ended up in that state when i logged back in. a /reload fixed it for me. But i will keep looking into this.

**Comment by MadSandwich** [comment]
@Spillmaker thanks, strange that reload help me too, but relog into the game not))
![image](https://user-images.githubusercontent.com/57759145/193466463-6cd3a817-d1e7-4d7f-b3bd-9b11976c679c.png)
And I do not see titles and descriptions, and that I suppose language problem) If you have a file with translations I can commit a russian variant for this, just say me the name of that file

**Comment by Fedekielle** [comment]
Is is loaded on the Addon list.

<img width="561" alt="Skærmbillede 2022-10-02 kl  19 15 26" src="https://user-images.githubusercontent.com/114223928/193467140-b4d80f08-693e-4c82-b099-6491a0f03a9c.png">

**Comment by Fedekielle** [comment]
Badges are enabled to

<img width="405" alt="Skærmbillede 2022-10-02 kl  19 19 19" src="https://user-images.githubusercontent.com/114223928/193467306-bc8f5a65-cc56-47bc-9757-019b8c273700.png">

**Comment by Fedekielle** [comment]
Settings for Bagnon

<img width="1047" alt="Skærmbillede 2022-10-02 kl  19 19 43" src="https://user-images.githubusercontent.com/114223928/193467317-d16b2c9e-8866-4231-b996-3f3dd666176c.png">

**Comment by Fedekielle** [comment]
@Spillmaker Let me know if you need any other info/screenshots to solve the problem :)

**Comment by Spillmaker** [comment]
Hello, i have been testing this locally and think i have found the cause of the error.

Will push out an update this weekend.

**Comment by MadSandwich** [comment]
@Spillmaker sounds great. And what about translations? May I help you in this?

**Comment by MadSandwich** [comment]
@Spillmaker thank you. What about translation? May I help you in this?

**Comment by Fedekielle** [comment]
@Spillmaker - I found out that the data broker plugin to see badges works in the bank. Maybe that helps to solve the issue with it not appearing on the bags?
-
<img width="1308" alt="Skærmbillede 2022-10-09 kl  00 01 28" src="https://user-images.githubusercontent.com/114223928/194729274-fc6474f9-edee-4b65-a4d6-0b802f7b6a3c.png">

**Comment by Smekolini** [comment]
Did u find out what caused the "Loading currencies...." bug? I am having that too

**Comment by thehallowedfire** [comment]
Hello. Any updates on the issue? Have the same problem, plugin doesn't work

**Comment by Spillmaker** [comment]
Hi, ive just deployed a new update who should fix an issue with the addon not loading properly at game launch and fixed an issue with it only using improper fonts on other regions clients.

The update is 2.1.0 and should be available at Wago and Curseforge shortly.

**Comment by Fedekielle** [comment]
@Spillmaker just updated to 2.1.0. I still can't see currencies in the inventory - only in bank

**Comment by Spillmaker** [comment]
@Fedekielle Its a very strange issue you have there. And since you currently is the only one with this perticlar issue i have to suspect that it may be because of other addons. Try to disable all addons expect the bagnon-suite and bagnon currnecies and see if it works then.

If not, give me a list of your addons and i could try to troubleshoot it. But yeah... If it works in the guildbank i dont see why it wouldnt work in the bags.

**Comment by Fedekielle** [comment]
@Spillmaker if I disable everything besides Bagnon, then i can see the currency on my bag, but I cant seem to find which Addon is causing the problem. When I turn everything on after i've had everything disabled, then I can still see the currencies, but if I then scroll between other data broker plugins via ><, then currencies dissapears.

<img width="576" alt="Skærmbillede 2022-10-15 kl  20 27 51" src="https://user-images.githubusercontent.com/114223928/196002482-79ddcf22-2cb2-49f4-ab0a-919c35029771.png">
<img width="578" alt="Skærmbillede 2022-10-15 kl  20 27 57" src="https://user-images.githubusercontent.com/114223928/196002484-016f75c2-95b9-43a1-a133-b6df5cea663b.png">
<img width="574" alt="Skærmbillede 2022-10-15 kl  20 28 03" src="https://user-images.githubusercontent.com/114223928/196002485-86ee8411-eef5-487d-91c5-5d4d24e83b1a.png">
<img width="575" alt="Skærmbillede 2022-10-15 kl  20 28 11" src="https://user-images.githubusercontent.com/114223928/196002487-0147ec98-cec4-4e6a-9346-d278e544b00c.png">
<img width="575" alt="Skærmbillede 2022-10-15 kl  20 28 19" src="https://user-images.githubusercontent.com/114223928/196002492-9d2e7ad6-dc12-488e-9f50-167b4e349cf0.png">

**Comment by Spillmaker** [comment]
@Fedekielle I notice that you get up Weakaura in the databroker, could you try disabling that and see what happens then?

What version of Weakaura are you using?

**Comment by thehallowedfire** [comment]
Thank you for update. Addon is working!
Though there is probably an issue with Honor icon. Should it be this small with a huge spacing after it?
![image](https://user-images.githubusercontent.com/112851853/196003850-60133e3e-ce0b-4238-97ae-9cfc26a46395.png)

The same small icon in tooltip as well
![image](https://user-images.githubusercontent.com/112851853/196003889-bf683faa-c337-472c-abe0-4f834130e4fc.png)

**Comment by Spillmaker** [comment]
@Fedekielle Think i found something now. Will look at it. Thanks for the help. IF i find a fix for it i will make a update on the Beta-channel.

@thehallowedfire I am aware of this issue. It is because the honor-points icons works differently than the others. Not a high prio to fix, but i should be able to take a look at it this weekend.

**Comment by Spillmaker** [comment]
@Fedekielle So this was an interesting one, turns out there was a bug that made Bagnon_Currencies interfere with other databrokers, but it seems like it was made more apparent after an update Bagnon released last month.

Ive fixed the issue and pushed out a new version that should be out shortly. You should start seeing it consistently now probably with more other databrokers as well.

**Comment by Spillmaker** [comment]
@thehallowedfire I moved your issue out in another ticket. #15 You can keep track of it there :)

**Comment by Fedekielle** [comment]
@Spillmaker - seems to work perfectly now. Thanks you so much! :)

**Comment by Spillmaker** [comment]
Glad to hear :) Feel free to open a new ticket if you find anything else :)

**Comment by thehallowedfire** [comment]
After the last update (v.2.2.0) plugin stopped working again. It just doesn't display in the bag window (I tried to click on the arrows but there is no currencies)

**Comment by Spillmaker** [comment]
> After the last update (v.2.2.0) plugin stopped working again. It just doesn't display in the bag window (I tried to click on the arrows but there is no currencies)

So i thinkt his is a issue with Bagnon itself. Because i see this issue happening even with Bagnon_currencies disabled.

often when you use the Previous button (<) you will only see 3 items, but if you use the Next button (>) you will se all of them.

Im trying to investigate this now but since it happens with other databroker plugins as well even with my addon disabled, im almost sure this is Bagnon related.
