### ISSUE TITLE
Addon not working as of today (03/10/2022)

### ISSUE THREAD

**Issue by Raisoshi** [Spillmaker/Bagnon_Currencies#14]
Usually when this happens I'll update it and it'll fix the issue but no luck today, can't even open my bags with the addon enabled, when I try to it gives me this error:

Date: 2022-10-03 15:01:53
ID: 2
Error occured in: Global
Count: 2
Message: ...\AddOns\Bagnon\common\Wildpants\classes\currency.lua line 23:
   attempt to concatenate field 'iconFileID' (a nil value)
Debug:
   [string "@Bagnon\common\Wildpants\classes\currency.lua"]:23: Set()
   [string "@Bagnon\common\Wildpants\classes\currencyTracker.lua"]:64: Layout()
   [string "@Bagnon\common\Wildpants\classes\currencyTracker.lua"]:42: RegisterEvents()
   [string "@Bagnon\common\Wildpants\classes\currencyTracker.lua"]:28:
      ...\Bagnon\common\Wildpants\classes\currencyTracker.lua:23
   [string "=(tail call)"]: ?
   [string "@Bagnon\addons\main\frame.lua"]:312: PlaceCurrencies()
   [string "@Bagnon\addons\main\frame.lua"]:96: Layout()
   [string "@Bagnon\addons\main\frame.lua"]:66: Update()
   [string "@Bagnon\addons\main\frame.lua"]:56: RegisterSignals()
   [string "@Bagnon\common\Wildpants\classes\frame.lua"]:19:
      ...ace\AddOns\Bagnon\common\Wildpants\classes\frame.lua:17
   [string "=(tail call)"]: ?
   [string "@Bagnon\common\Wildpants\classes\inventory.lua"]:21:
      ...AddOns\Bagnon\common\Wildpants\classes\inventory.lua:20
   [string "=[C]"]: Show()
   [string "@Bagnon\common\Wildpants\api\frames.lua"]:85: Show()
   [string "@Bagnon\common\Wildpants\api\frames.lua"]:77:
      ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:76
   [string "=(tail call)"]: ?
   [string "=(tail call)"]: ?
   [string "@Bagnon\common\Wildpants\features\autoDisplay.lua"]:82: ToggleBackpack()
   [string "@Interface/FrameXML/MainMenuBarBagButtons.lua"]:54: BackpackButton_OnClick()
   [string "*:OnClick"]:4:
      [string "*:OnClick"]:1
Locals:
self = <unnamed> {
 0 = <userdata>
 frame = BagnonInventoryFrame1 {
 }
}
data = "Emblem of Heroism"
(*temporary) = <function> defined =[C]:-1
(*temporary) = <unnamed> {
 0 = <userdata>
 frame = BagnonInventoryFrame1 {
 }
}
(*temporary) = nil
(*temporary) = "|T"
(*temporary) = nil
(*temporary) = ":15:15:2:0|t  "
(*temporary) = "attempt to concatenate field 'iconFileID' (a nil value)"

AddOns:
  Swatter, v3.4.6817 (SwimmingSeadragon)
  Altoholic, v2.5.008
  AucAdvanced, v3.4.6825 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6803 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6805 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6809 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6806 (SwimmingSeadragon)
  AucStatSimple, v3.4.6807 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6808 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6810 (SwimmingSeadragon)
  Auctionator, v9.2.41
  BagBrother, v
  Bagnon, v10.0.0
  BagnonBoE, v1.0.45-Release
  BagnonCurrencies, v2.0.0
  Bartender4, v4.11.6-20-gac40e29
  BeanCounter, v3.4.6811 (SwimmingSeadragon)
  DataStore, v2022.06.05
  DataStoreAgenda, v2.5.008
  DataStoreAuctions, v2.5.008
  DataStoreCharacters, v2022.06.05
  DataStoreContainers, v2.5.008
  DataStoreCrafts, v2.5.008
  DataStoreInventory, v2.5.008
  DataStoreMails, v2022.06.05
  DataStoreQuests, v2.5.008
  DataStoreReputations, v2.5.008
  DataStoreSpells, v2022.06.05
  DataStoreTalents, v2.5.008
  DBMCore, vb953898
  DBMStatusBarTimers, vb953898
  DBMVPVEM, v1b93adf
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v3.4.6821 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6813 (SwimmingSeadragon)
  GatherMate2, v1.46.3-classic
  Guidelime, v3.001
  GuidelimeBusteas160leveling, v3.1.0-Release
  GuidelimeFlymolosOutlandLevelingGuide, v3.0.1-Release
  GuideLimeTUGsWOTLK, v3.45
  Informant, v3.4.6814 (SwimmingSeadragon)
  LeatrixMaps, v3.0.11
  LeatrixPlus, v3.0.20
  LibStub, v
  LibTouristClassic10, v
  ModernTargetFrame, v1.11
  OmniCC, v9.2.1
  OmniCD, v3.4.0.2723
  Pawn, v2.7.2
  Postal, vv3.8.2
  Prat30, v3.9.1
  Prat30Libraries, v
  Quartz, v3.6.12-1-g270f58f
  Questie, v7.3.0
  Recount, vv3.4.0a
  Scrap, v9.2.1
  SexyMap, vv9.2.11
  SimpleItemLevel, v1
  SlideBar, v3.4.6815 (SwimmingSeadragon)
  Stubby, v3.4.6816 (SwimmingSeadragon)
  TitanClassic, v1.5.3.30400
  TitanClassicAmmo, v1.5.3.30400
  TitanClassicBag, v1.5.3.30400
  TitanClassicClock, v1.5.3.30400
  TitanClassicGold, v1.5.3.30400
  TitanClassicLocation, v1.5.3.30400
  TitanClassicLootType, v1.5.3.30400
  TitanClassicPerformance, v1.5.3.30400
  TitanClassicRegen, v1.5.3.30400
  TitanClassicRepair, v1.5.3.30400
  TitanClassicVolume, v1.5.3.30400
  TitanClassicXP, v1.5.3.30400
  TomTom, vv3.1.4
  WeakAuras, v4.1.4
  WowheadQuickLink, v2.13.10
  ZoneInfoClassic, v1.0
  BlizRuntimeLib_enUS v3.4.0.30400 <none>
  (ck=9b5)

**Comment by Spillmaker** [comment]
Hi, this error-message is not from bagnon_currencies, but looks to be from the Main Bagnon-addon. (Or one of its libraries)
