### ISSUE TITLE
Localization issues

### ISSUE THREAD

**Issue by Spillmaker** [Spillmaker/Bagnon_Currencies#16]
@Spillmaker thanks, strange that reload help me too, but relog into the game not))
![image](https://user-images.githubusercontent.com/57759145/193466463-6cd3a817-d1e7-4d7f-b3bd-9b11976c679c.png)
And I do not see titles and descriptions, and that I suppose language problem) If you have a file with translations I can commit a russian variant for this, just say me the name of that file

_Originally posted by @MadSandwich in https://github.com/Spillmaker/Bagnon_Currencies/issues/13#issuecomment-1264688198_

**Comment by Spillmaker** [comment]
@MadSandwich I moved this issue out in a new ticket.

This should be fixed, could you confirm? :)

**Comment by MadSandwich** [comment]
@Spillmaker I would be glad to confirm, but after update there is no longer data broker for currencies in bags

**Comment by Spillmaker** [comment]
> @Spillmaker I would be glad to confirm, but after update there is no longer data broker for currencies in bags

Hi, could you try using the Next button (>) to browse into Bagnon Currencies? It seems like the previous button (<) may be bugged.

**Comment by MadSandwich** [comment]
@Spillmaker, thank you for the suggesion. Yes, via next button I was able to find currencies and localization issue is no longer exist.
![image](https://user-images.githubusercontent.com/57759145/196027515-49d91c7c-3eb6-498e-a107-3a936e01e4df.png)
The issue can ba closed.
