### ISSUE TITLE
Currencies showing up as green square and zero

### ISSUE THREAD

**Issue by Gorpas** [Spillmaker/Bagnon_Currencies#17]
![SteelSeriesGG_5RkFwgOHy8](https://user-images.githubusercontent.com/116466348/197364406-e3a492ae-186a-46c1-aa0b-aa59c9c124b2.png)

All other addons are disabled

**Comment by thehallowedfire** [comment]
It happened to me too, but after the last update of Bagnon itself now Data Broker plugin is not needed. Bagnong has built-in currencies. 
![image](https://user-images.githubusercontent.com/112851853/197445656-564d041b-940a-4f45-97fe-eccb21bdbbe7.png)

**Comment by Spillmaker** [comment]
Both of the screenshots shows the bagnon now built-in tracker, and not the databroker. Closing this since its not related to this addon.
