### ISSUE TITLE
Shadowlands

### ISSUE THREAD

**Issue by Borinius** [Spillmaker/Bagnon_Currencies#4]
Will there be an update for Shadowlands and 9.0.1?

**Comment by AlexL1118** [comment]
I suggest few modifications for Shadowlands in file "Bagnon_Currencies.lua":

Line 17:
Was:
`	if(GetBackpackCurrencyInfo(i)) then`
Now:
`	if(C_CurrencyInfo.GetBackpackCurrencyInfo(i)) then`

Line 31:
Was:
`	local name, count, icon = GetBackpackCurrencyInfo(i);`
Now:
`	local info = C_CurrencyInfo.GetBackpackCurrencyInfo(i)`
`	local count = info.quantity`
`	local icon = info.iconFileID`

Lines 48--49:
Was:
`	local name, count, icon, itemID  = GetBackpackCurrencyInfo(i);`
`	local name, amount, texturePath, earnedThisWeek, weeklyMax, totalMax, isDiscovered = GetCurrencyInfo(itemID);`
Now:
`	local info = C_CurrencyInfo.GetBackpackCurrencyInfo(i)`
`	local itemID = info.currencyTypesID`
`	local info = C_CurrencyInfo.GetCurrencyInfo(itemID)`
`	local icon = info.iconFileID`
`	local name = info.name`
`	local amount = info.quantity`
`	local earnedThisWeek = info.quantityEarnedThisWeek`
`	local weeklyMax = info.maxWeeklyQuantity`
`	local totalMax = info.maxQuantity`

After these modifications the addon began to work for me in Shadowlands prepatch (I tested with Bagnon).

**Comment by Borinius** [comment]
The addon is no longer spitting errors, well done sir! Many thanks :)

**Comment by Spillmaker** [comment]
There is a new version available.
