### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Horygor** [Spillmaker/Bagnon_Currencies#7]
The addon doesn't show my currencies with last Shadowlands patch

**Comment by EugeneLeclerc** [comment]
Same. Up-to-date Bagnon and Bagnon Currencies but I cant see my currencies. I'm available if its not a general issue and if you need details.

**Comment by journeym** [comment]
Confirmed, doesnt work.
Anyone able to fix that?

**Comment by Spillmaker** [comment]
Kinda difficult to fix something when the issue is "not working" Would need more information than that.

However i pushed an update to fix #8 now so try to update and see if it works now.
