### ISSUE TITLE
LUA Error When Deselecting & Reselecting Currency

### ISSUE THREAD

**Issue by reale411** [Spillmaker/Bagnon_Currencies#8]
Message: ...rface\AddOns\Bagnon_Currencies\Bagnon_Currencies.lua:39: attempt to index local 'info' (a nil value)
Time: Wed Mar 31 16:55:25 2021
Count: 16
Stack: ...rface\AddOns\Bagnon_Currencies\Bagnon_Currencies.lua:39: attempt to index local 'info' (a nil value)
[string "@Interface\AddOns\Bagnon_Currencies\Bagnon_Currencies.lua"]:39: in function <...rface\AddOns\Bagnon_Currencies\Bagnon_Currencies.lua:33>
[string "@Interface\AddOns\Bagnon_Currencies\Bagnon_Currencies.lua"]:107: in function `?'
[string "@Interface\AddOns\Bagnon_Currencies\Bagnon_Currencies.lua"]:120: in function <...rface\AddOns\Bagnon_Currencies\Bagnon_Currencies.lua:119>

Locals: text = <table> {
}
(for index) = 1
(for limit) = 1
(for step) = 1
i = 1
info = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = <table> {
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = ""
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'info' (a nil value)"
GetNumWatchedTokens = <function> defined @Interface\AddOns\Blizzard_TokenUI\Blizzard_TokenUI.lua:210
GetBackpackCurrencyInfo = <function> defined =[C]:-1
tinsert = <function> defined =[C]:-1
strjoin = <function> defined =[C]:-1
createIconString = <function> defined @Interface\AddOns\Bagnon_Currencies\Bagnon_Currencies.lua:25
dataObject = <table> {
}
unpack = <function> defined =[C]:-1

**Comment by Spillmaker** [comment]
I pushed a new update that fixes this now.
